### ISSUE TITLE
Feature request implement "port status"

### ISSUE THREAD

**Issue by chris4474** [nitram509/ntgrrc#79]
Implement "port status" to display the status of ports as shown by the main screen of the web interface. Output formats would be similar to the formats supported by the other commands (md, json).
Great work. Thank you.

**Comment by nitram509** [comment]
@chris4474 
I'm working on feature completeness for GS316 on a branch.
I added the fields 'Port Status' and 'Link Speed' in the `port settings` command,
because the port status and port settings have a lot of overlap.

You can try this branch on your own ... is this what you're looking for?
 https://github.com/nitram509/ntgrrc/tree/feature/gs316-port-set

Example:
`ntgrrc port settings --address=192.168.0.239`

**Comment by nitram509** [comment]
Considered 'done' with latest release https://github.com/nitram509/ntgrrc/releases/tag/v0.12.0

**Comment by chris4474** [comment]
Thank you. Yes I was interested in the "Available/Up" port information as this how I detect that my devices are fully shut down. Thank you for that!
